sudo: required
language: python
python:
  - "3.5"
services:
  - mysql
before_install:
  - mysql -u root --password="" < test_environment/create_db.sql
  - wget db-env.mienkofax.eu/measured_klarka.sql.tar.gz
  - wget db-env.mienkofax.eu/measured_peto.sql.tar.gz
  - tar -xvzf measured_klarka.sql.tar.gz
  - tar -xvzf measured_peto.sql.tar.gz
  - mysql -u root -p demo --password="" < measured_klarka.sql
  - mysql -u root -p demo --password="" < measured_peto.sql
  - rm *.sql *.gz
install:
  - pip install -r requirements.txt
script:
  - python examples2/0000_db_tests/run.py
  - python examples2/0100_klarka_values_all_graphs/run.py
