sudo: required
language: python
python:
  - "3.5"
services:
  - mysql
before_install:
  - sudo apt update
  - sudo apt install python3-tk
  - mysql -u root --password="" < test_environment/create_db.sql
  - wget db-env.mienkofax.eu/measured_klarka.sql.tar.gz
  - wget db-env.mienkofax.eu/measured_klarka_shower.sql.tar.gz
  - wget db-env.mienkofax.eu/measured_filtered_peto.sql.tar.gz
  - tar -xvzf measured_klarka.sql.tar.gz
  - tar -xvzf measured_klarka_shower.sql.tar.gz
  - tar -xvzf measured_filtered_peto.sql.tar.gz
  - mysql -u root -p demo --password="" < measured_klarka.sql
  - mysql -u root -p demo --password="" < measured_klarka_shower.sql
  - mysql -u root -p demo --password="" < measured_filtered_peto.sql
  - rm *.sql *.gz
install:
  - pip install -r requirements.txt
script:
  - python examples2/0000_db_tests/run.py
  - python examples2/0100_open_close_all_graphs/run.py
  - python examples2/0101_shower_all_graphs/run.py
  - python examples2/0102_sh_diff_graphs_analysis/run.py
  - python examples2/0103_open_ventilation_length_detector/run.py
  - python examples2/0104_open_detector/run.py
  - python examples2/0200_open_close_all_graphs/run.py
  - python examples2/0201_co2_delays_histogram/run.py
  - python examples2/0202_open_detector/run_co2.py
  - python examples2/0202_open_detector/run_co2_t_h.py
  - python examples2/0202_open_detector/run_co2_t_h_out.py
